name: Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2	
      - name: Create ZIP archive
        run: mkdir -p tmp_dist && cd custom_components/marees_france/ && zip -r ../../tmp_dist/marees_france.zip .
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          generate_release_notes: true
          files: tmp_dist/*.zip