name: Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2	
      - name: "Set version number"
        run: |
          yq -i -o json '.version="${{ github.event.release.tag_name }}"' \
            "${{ github.workspace }}/custom_components/marees_france/manifest.json"
      - name: Commit new version
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "
          git config --global user.name "KipK"
          git config --global user.email "KipK@nospam.org"
          git add custom_components/marees_france/manifest.json
          git commit -m "Bump version"
          git push

      - name: Create ZIP archive
        run: mkdir -p tmp_dist && cd custom_components/marees_france/ && zip -r ../../tmp_dist/marees_france.zip .
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          generate_release_notes: true
          files: tmp_dist/*.zip